[package]
name = "campfire-writing-linux-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
md5 = "0.8.0"
quick-xml = { version = "0.38.3", features = ["serialize", "tokio"] }
reqwest = { version = "0.12.24", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_norway = "0.9.42"
tokio = { version = "1.48.0", features = ["full"] }
